# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

matrix:
  include:
  - r: devel
  - r: oldrel
  - r: release

    after_success:
    - Rscript -e 'covr::codecov()'

    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("rstudio/rmarkdown")'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true

  - r: 4.0
  - r: 3.6
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2

# environment variables set for all builds
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_FORCE_SUGGESTS_=true
  - _R_CHECK_CRAN_INCOMING_=true

after_success:
  - Rscript -e 'covr::codecov()'
